sudo: required
node_js:
 - "8"
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start
addons:
  chrome: stable
install: 
  - npm install
script:
  - npm install codecov -g
  - npm test --code-coverage
after_success:
  - codecov
cache:
  directories:
    - "node_modules"